config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
devise_for :users, controllers: { sessions: 'users/sessions' }

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :produits, only: [:index, :show] do
    resources :reviews, only: :create
  end
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :gammes, only: [:show]
  resources :contacts, only: [:new, :create]
  resources :orders, only: [:index, :create,:show,:update, :destroy] do
    resources :payments, only: :new
  end

  root to: 'pages#home'

  get 'qui_sommes_nous', to: 'pages#qui_sommes_nous', as: :qui_sommes_nous
  get 'aide',            to: 'pages#aide',             as: :aide
  get 'mentions_legales',to: 'pages#mentions_legales',as: :mentions_legales
  get 'CGV',             to: 'pages#CGV',             as: :cgv
  get 'paiement_reussi', to: 'pages#payment_success', as: :payment_success
  get 'paiement_annule', to: 'pages#payment_cancel', as: :payment_cancel
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/views/shared/_back_to_top.html.erb
<div class="back_to_top">
  <button  id="backToTop" title="Back to Top"><i class="fas fa-chevron-up"></i></button>
  <p class="back_top_text hidden-xs">Haut de page</p>
</div>

app/views/shared/_cart_text.html.erb
<%= link_to  cart_path, class: "header-cart" do %>
  <i class="fas fa-shopping-cart"></i>
  <p class="nb-products hidden-sm hidden-md hidden-lg"><%= "(#{current_order.order_items.size})"%></p>
  <div class="cart-review">
  <p class="hidden-xs">Panier</p>
  <p class="hidden-xs"><%= "#{current_order.order_items.size} Article(s)"%></p>
  </div>
<% end %>

app/views/shared/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer" >
  <section class="reinsurance">
    <div class="container">
      <div class="row" id="reinsurance-row">
        <div class="col-xs-6 col-sm-3 reinsurance-item">
          <div class="suppliers">
            <%= image_tag "quality2.png", class: "icon-footer", alt: "la cabane de maï- Fournisseurs de qualité"%>
            <p>Fournisseurs et produits <br>
            triés sur le volet</p>
          </div>
        </div>
        <div class="col-xs-6 col-sm-3 reinsurance-item">
          <div class="selection">
            <%= image_tag "eco.png", class: "icon-footer hidden-xs hidden-sm", alt: "la cabane de maï - produits naturels"%>
            <%= image_tag "craft.png", class: "icon-footer", alt: "la cabane de maï - produits artisanaux"%>
            <p>Sélections exclusives de cadeaux <br>
            naturels et artisanaux</p>
          </div>
        </div>
        <div class="col-xs-6 col-sm-3 reinsurance-item">
          <div class="delivery">
            <%= image_tag "truck1.png", class: "icon-footer", alt: "la cabane de maï - Livraison"%>
            <p>Livraison Colissimo<br>
              (offerte à partir de 50 €)</p>
          </div>
        </div>
        <div class="col-xs-6 col-sm-3 reinsurance-item">
          <div class="security">
            <%= image_tag "lock.png", class: "icon-footer", id:"lock", alt: "la cabane de maï - Paiement sécurisé"%>
            <p>Paiement sécurisé</p>
            <a href="https://stripe.com/fr-us" target="_blank" rel="noopener noreferrer"><%= cl_image_tag("powered_by_stripe1.png", id: "stripe-logo", alt: "stripe")  %></a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="links">
    <div class="container">
      <div class="row links-items">
        <div class="col-xs-6 col-sm-3 items-top" id="item-1">
          <h3>La cabane</h3>
          <ul>
            <li><%= link_to "Qui sommes-nous", qui_sommes_nous_path, class: "footer-item footer-link"%></li>
            <li><%= link_to "Nous contacter", new_contact_path, class: "footer-item footer-link"%></li>
          </ul>
        </div>
        <div class="col-xs-6 col-sm-3 items-top">
          <h3>Aide</h3>
          <ul>
            <li><%= link_to "FAQ", aide_path, class: "footer-item footer-link"%></li>
          </ul>
        </div>
        <div class="col-xs-6 col-sm-3">
          <h3>Legal</h3>
          <ul>
            <li><%= link_to "CGV", cgv_path, class: "footer-item footer-link"%></li>
            <li><%= link_to "Mentions légales", mentions_legales_path, class: " footer-item footer-link"%></li>
          </ul>
        </div>
        <div class="col-xs-6 col-sm-3" id="shop-details">
          <h3>Contact</h3>
          <ul>
            <li><a class="footer-item footer-link" href="tel:+33642225711">+33 6 42 22 57 11</a></li>
            <li class="footer-item"><p>16 avenue pasteur<br> 33510, Andernos-les-Bains </p></li>
            <li><a class="footer-item footer-link" id="email-footer" href="mailto:contact@lacabanedemaii.com">contact@lacabanedemaii.com</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-social">
      <p>Suivez nous sur</p>
      <a href="https://www.facebook.com/lacabanedemaii16/" target="_blank" rel="noopener noreferrer"><i class="fab fa-facebook-f"></i></a>
      <a href="https://www.instagram.com/la_cabane_de_maii/?hl=fr" target="_blank" rel="noopener noreferrer"><i class="fab fa-instagram"></i></a>
    </div>
  </section>
  <hr class="separator3">
  <section class="footer-bottom">
    <div id="flex-container">
      <div id="bottom-footer-row">
        <%= image_tag "logo.jpg", class: "logo", alt: "la cabane de maï"%>
      </div>
      <div id="copyright">
        <p>© 2019 La cabane de Maï. Site réalisé par <a href="https://www.alexgwebdev.com/" target="_blank" rel="noopener noreferrer"><%= image_tag "alexgwebdev.png", class: "logo-alex", alt: "Alex G - Web developer"%></a></p>
      </div>
    </div>
  </section>
</footer>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar-fixed-top">
  <div class="dropdown-background">
    <span class="arrow-style"></span>
  </div>
  <div class="navbar-top">
    <div class="logo">
      <%= link_to root_path do %>
      <%= image_tag "logo.jpg",class: "logo", alt: "la cabane de maï"%>
      <% end %>
    </div>
    <div class="hidden-xs hidden-sm">
      <div class="form-group">
        <%= render 'shared/search', query: params[:search] %>
      </div>
    </div>
    <div class="navbar-right">
      <div class="cart-text">
        <%= render "shared/cart_text" %>
        <p class="free_delivery hidden-xs">Frais de port offerts à partir de 50 €</p>
        <div class="dropdown-style">
          <% if current_order.order_items.size == 0 %>
          <div class="cart-anim-empty">
            <p class="text-center">Votre panier est vide</p>
            <p class="text-center"><em>Voir <%= link_to "les produits", produits_path %></em></p>
          </div>
          <% else %>
          <ul class="list-unstyled">
            <% current_order.order_items.each do |order_item| %>
            <li>
              <h6 class="text-center"><strong><%= order_item.produit.nom %></strong></h6>
              <div class="cart-anim">
              <%= cl_image_tag order_item.produit.photo, crop: :thumb, class: "pic-cart-anim" %>
                <div class="cart-anim-right">
                  <p> Qantité : <%= order_item.quantity %></p>
                  <p>Px unit : <span style="color: green"><%= humanized_money(order_item.unit_price)%> <%= currency_symbol %></span></p>
                </div>
              </div>
            </li>
            <hr class="sep">
            <% end %>
            <h5 class="text-right">Total : <span id="price" style="color: green"><%= humanized_money(current_order.total_price) %> <%= currency_symbol %></span></h5>
          <% end %>
          </ul>
        </div>
      </div>
    <% if user_signed_in? %>
      <div class="right hidden-xs hidden-sm">
        <%= link_to "Mes commandes", orders_path, class: "navbar-item navbar-link"  %>
      </div>
      <div class="carret dropdown hidden-xs hidden-sm">
        <i class="fas fa-caret-down dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu-bis">
          <span class="arrow"></span>
          <li><%= link_to t(".profile", default: "Mon compte"),edit_user_registration_path, class: "navbar-item navbar-link" %></li>
          <li><%= link_to t(".sign_out", default: "Déconnexion"),destroy_user_session_path, method: :delete, class: "navbar-item navbar-link" %></li>
        </ul>
      </div>
    </div>
    <div class="icons-right navbar-item hidden-md hidden-lg">
      <div class="dropdown dropdown-search">
        <i class="fa fa-search dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu-bis">
          <span class="arrow"></span>
          <li>
            <div class="form-group">
              <%= render 'shared/search', query: params[:search] %>
            </div>
          </li>
        </ul>
      </div>
      <i class="fa fa-bars burger"></i>
      <div class="sidenav">
        <i class="far fa-times-circle closebtn"></i>
        <ul class="">
          <li><%= link_to "Mes commandes", orders_path, class: "navbar-item navbar-link"  %></li>
          <li><%= link_to t(".profile", default: "Mon compte"),edit_user_registration_path, class: "navbar-item navbar-link" %></li>
          <li><%= link_to t(".sign_out", default: "Déconnexion"),destroy_user_session_path, method: :delete, class: "navbar-item navbar-link" %></li>
          <li role="separator" class="divider"></li>
          <% @prod_gammes.each do |g| %>
          <li>
            <%= link_to  gamme_path(g), class: "navbar-item navbar-link", id: "#{g.id}" do %>
              <%= g.name %>
            <% end %>
          <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login link (when logged out) -->
      <div class="icons-right navbar-right">
        <div class="right hidden-xs hidden-sm">
          <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-item navbar-link" %>
        </div>
      </div>
      <div class="icons-right navbar-item hidden-md hidden-lg">
        <div class="dropdown dropdown-search">
          <i class="fa fa-search dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu-bis">
            <span class="arrow"></span>
            <li>
              <div class="form-group">
                <%= render 'shared/search', query: params[:search] %>
              </div>
            </li>
          </ul>
        </div>
        <i class="fa fa-bars burger"></i>
        <div class="sidenav">
          <i class="far fa-times-circle closebtn"></i>
          <ul>
            <li>
              <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-item navbar-link" %>
            </li>
            <li role="separator" class="divider"></li>
            <% @prod_gammes.each do |g| %>
              <li>
                <%= link_to  gamme_path(g), class: "navbar-item navbar-link", id: "#{g.id}" do %>
                  <%= g.name %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</nav>

app/views/shared/_search.html.erb
<div class="search-prod">
  <%= form_tag produits_path, method: :get do %>
    <%= text_field_tag :search,
      params[:search],
      class: "search-prod form-search",
      id: "product_search",
      placeholder: "Cherchez un produit..." %>
    <%= button_tag(type: "submit", class: "search_submit") do %>
    <i class='fa fa-search'></i>
    <% end %>
  <% end %>
</div>

app/views/shared/_tab.html.erb
<div class="container">
  <div class="tabs tabs-show">
    <% @prod_gammes.each do |g| %>
      <%= link_to  gamme_path(g), class: "tab", id: "#{g.id}" do %>
        <h3><%= g.name %></h3>
      <% end %>
    <% end %>
  </div>
  <hr class=separator2>
</div>