config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
devise_for :users, controllers: { sessions: 'users/sessions' }

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :produits, only: [:index, :show] do
    resources :reviews, only: :create
  end
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :gammes, only: [:show]
  resources :contacts, only: [:new, :create]
  resources :orders, only: [:index, :create,:show,:update, :destroy] do
    resources :payments, only: :new
  end

  root to: 'pages#home'

  get 'qui_sommes_nous', to: 'pages#qui_sommes_nous', as: :qui_sommes_nous
  get 'aide',            to: 'pages#aide',             as: :aide
  get 'mentions_legales',to: 'pages#mentions_legales',as: :mentions_legales
  get 'CGV',             to: 'pages#CGV',             as: :cgv
  get 'paiement_reussi', to: 'pages#payment_success', as: :payment_success
  get 'paiement_annule', to: 'pages#payment_cancel', as: :payment_cancel
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    add_breadcrumb "accueil", :root_path
    add_breadcrumb "produits", produits_path
    add_breadcrumb "panier", cart_path
    @order = current_order
    @order_items = current_order.order_items
    @order_items.each  do |order_item|
      if order_item.produit.active == false
        order_item.destroy
        flash[:alert] = "Le produit #{order_item.produit.nom} est indisponible. Il a été retiré du panier"
        redirect_to cart_path
      end
    end
  end
end

app/views/carts/_cart_row.html.erb
<div class="cart-row">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 cart-list">
        <div class="product">
        <div class="name text-center">
          <h6><%= produit.nom %></h6>
        </div>
          <%= link_to produit_path(produit) do %>
          <%= cl_image_tag produit.photo, crop: :thumb, class: "cart-pic" %>
          <% end %>
        </div>
        <div class="unit hidden-xs text-center">
          <h6>Prix unitaire :  <span id="price" style="color: green"><%= humanized_money(order_item.unit_price)%> <%= currency_symbol %></span></h6>
        </div>

        <div class="quantity text-center">
            <%= simple_form_for order_item, remote: true do |f| %>
            <p>Quantité : </p><%= f.input :quantity,
                                        collection: 1..order_item.available_quantity,
                                        label: false,
                                        default: 1,
                                        value: order_item.quantity,
                                        class: "form-control" %>
            <%= f.hidden_field :produit_id, value: produit.id, id: produit.id %>
            <%= f.button :submit, "Modifier qté", class: "btn btn-block panier q", form_class: "update_quantity" %>
            <% end %>
        </div>

        <div class="delete">
          <%= button_to order_item, method: :delete, remote: true, form_class: "delete-item", data: { name: "#{order_item.produit.nom}" } do %>
          <span class="far fa-trash-alt"></span>
          <% end %>
        </div>

        <div class="total text-center hidden-xs">
          <h6>Total : <span id="price" style="color: green"><%= humanized_money(order_item.total_price) %> <%= currency_symbol %></span></h6>
        </div>
      </div>
      <div class="total text-right hidden-md hidden-lg hidden-sm">
          <h6>Total : <span id="price" style="color: green"><%= humanized_money(order_item.total_price) %> <%= currency_symbol %></span></h6>
      </div>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<div class="shopping-cart-show">
  <div class="shopping-cart">
    <div class="breadcrumbs back">
      <%= render_breadcrumbs :separator => ' > ' %>
    </div>
    <h1 id="cart-title" class="page-title text-center">Votre Panier</h1>
    <div class="cart-space">
      <% if !@order_item.nil? && @order_item.errors.any? %>
        <div class="alert alert-danger">
          <ul>
          <% @order_item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <% if @order_items.size == 0 %>
        <div class="empty-cart container">
          <h4 class="text-center">Votre panier est vide</h4>
          <p class="text-center">Retourner voir <%= link_to "les produits", produits_path %></p>
          <hr class="sep">
        </div>
      <% else %>
        <% @order_items.each do |order_item| %>
          <%= render 'carts/cart_row', produit: order_item.produit, order_item: order_item, show_total: true %>
          <div class="container prod-line">
            <hr class="separator2">
          </div>
        <% end %>
      <% end %>
    </div>
    <div class=" container cart-bottom">
      <div class="container delivery-fields">
        <h1 id="deliv-title" class="page-title text-center">Détails de livraison</h1>
        <div class="row">
          <div class="col-xs-12">
            <div class="form-login form-deliv">
              <%= simple_form_for @order do |f| %>
                <%= f.error_notification %>
                <%= f.input :client_name, required: true, placeholder: "Jean Blaguin", autofocus: true, label: "Nom", error: 'Ce champ est obligatoire.' %>
                <hr class="sep">
                <label class="autocomplete-text text-center">Entrez votre adresse afin de remplir automatiquement les champs ci-dessous</label><br>
                <div id="locationField">
                  <input id="autocomplete" class="form-control" placeholder="Entrez votre adresse ici" type="text" autocomplete="off" ></input>
                </div>
                <hr class="sep">
                <div class="form-inline deliv-street">
                  <%= f.input :deliv_adress_nb, required: true, placeholder: "8", autofocus: true, label: "Adresse", input_html: {id: "street_number"}, error: 'Ce champ est obligatoire.' %>
                  <%= f.input :deliv_adress, required: true, placeholder: "avenue des champs", autofocus: true, label: false, input_html: {id: "route"}, error: 'Ce champ est obligatoire.' %>
                </div>
                <div class="form-inline deliv-city">
                  <%= f.input :deliv_adress_zip_code, required: true, placeholder: "75000", autofocus: true, label: "ville", input_html: {id: "postal_code"}, error: 'Ce champ est obligatoire.' %>
                  <%= f.input :deliv_adress_city, required: true, placeholder: "Paris", autofocus: true, label: false, input_html: {id: "locality"}, error: 'Ce champ est obligatoire.' %>
                </div>
                <div class="form-inline deliv-country">
                  <%= f.input :deliv_adress_pays, required: true, placeholder: "France", autofocus: true, label: "Pays", input_html: {id: "country"}, error: 'Ce champ est obligatoire.' %>
                </div>
                <%= f.input :deliv_adress_details, placeholder: "Entrée, escalier...", autofocus: true, label: "Détails complémentaires" %>
                <%= f.button :submit, "Confirmer l'adresse de livraison", class: "btn-success details-btn" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="cart-bill">
        <div class="row">
          <div class="col-xs-12 price-resume">
            <div class="sous-total text-right">
              <h6>Sous-Total : <span><%= humanized_money(current_order.subtotal) %> <%= currency_symbol %></span></h6>
            </div>
            <div class="fdp text-right">
              <% if (current_order.subtotal < 50) %>
                <h6>Frais de port : <span><%= humanized_money(current_order.shipping) %> <%= currency_symbol %></span></h6>
                <p class="fdp-text"> plus que <strong><%= humanized_money(current_order.free_shipping)%> <%= currency_symbol %></strong> pour bénéficier des frais de port gratuits</p>
              <% else %>
                <h6>Frais de port : <span><%= humanized_money(0) %> <%= currency_symbol %></span></h6>
                <p class="fdp-text">Frais de ports offerts</p>
              <% end %>
            </div>
            <div class="full-total text-right">
              <h4><strong>TOTAL : <span style="color: green"><%= humanized_money(current_order.total_price) %> <%= currency_symbol %></span></strong></h4>
            </div>
          </div>
        </div>
          <div class="order-checkout">
            <% if (current_order.subtotal > 0) %>
              <div class="finalize text-right">
                <%= form_tag orders_path do %>
                <%= hidden_field_tag 'order_items_id', @order_items.ids %>
                <%= submit_tag 'Finaliser la commande', class: "btn btn-finalize" %>
                <% end %>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/back_to_top' %>